### ISSUE TITLE
Set up instructions outdated

### ISSUE THREAD

**Issue by roloyar** [superdesk/superdesk#1103]
Hey guys! Really cool project! Can't wait to get my hands on a public demo! Which is why trying to set up myself :) I am using am Amazon EC2 server, thus I am not using 127.0.0.1, but instance's IP. The README.MD has links to lines in **superdesk/blob/master/docker/docker-compose.yml.sh**, but this file does not exist. Where should I make changes? **superdesk/blob/master/docker/common.yml**? **superdesk/blob/master/docker/run_e2e_tests.sh**? Both? Thanks for your answer!

**Comment by petrjasek** [comment]
hey, it should be in `superdesk/blob/master/docker/common.yml`. can you try?

**Comment by roloyar** [comment]
Yep, that did work for me, thanks! Also, I think it makes sense to warn people that they would need better set up than what Amazon free tier offers. Mango would not work for me on a free 1 CPU 1 Gb RAM and 8 Gb storage cloud instance, had to go with bigger specks. But maybe it's obvious and it's just my lack of experience.
