### ISSUE TITLE
docker doesn't  launch

### ISSUE THREAD

**Issue by nahuelange** [superdesk/superdesk#1424]
Hi,
We wanted to try superdesk using your docker demo…
When it tries to run the elasticsearch container docker throw an error:
`Cannot start container d28eee1b7b6b590c268079a400a0c6fcb66a373e3464d7d180a3253c2a50b107: [8] System error: exec format error`

**Comment by petrjasek** [comment]
@actionless can you pls check this?

**Comment by actionless** [comment]
@nahuelange , please paste output of the following commands:
```
uname -a
docker -v
docker ps
```

**Comment by nahuelange** [comment]
Hi,
There is:
```
~# uname -a
Linux 4.3.0-040300-generic #201511020846 SMP Mon Nov 2 14:02:08 UTC 2015 i686 i686 i686 GNU/Linux
~# docker -v
Docker version 1.6.2, build 7c8fca2
~# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

**Comment by actionless** [comment]
@nahuelange 
> i686

no way to run docker there, please proceed with a manual installation, you can just execute the steps from `Dockerfile` one by one in your terminal for the installation

@petrjasek 
do we need it in superdesk? https://github.com/verifiedpixel/verifiedpixel/blob/master/.travis.yml#L79-L90
