### ISSUE TITLE
docker-local-demo.sh fails to install docker-py on RHEL 7

### ISSUE THREAD

**Issue by timgws** [superdesk/superdesk#2005]
I am guessing this is related to https://github.com/docker/docker-py/issues/1019

To get `docker-local-demo.sh` to work, I added the following two lines to https://github.com/superdesk/superdesk/blob/master/scripts/docker-local-demo.sh#L14

pip install -U setuptools
pip install functools32 ipaddress

Note, the second line may not be needed.

**Comment by actionless** [comment]
could you please check more detailed regarding the second line? `pip install functools32 ipaddress`

**Comment by timgws** [comment]
Sure @actionless.

When running './docker-local-demo.sh', `docker-py` failed to install due to the version of `setuptools` being too old.

I added `pip install -U setuptools` to the script so that `docker-py` could be installed successfully by `pip`.

This worked, but `pip` failed to install some other requirements due to `functools32` and `ipaddress` missing from the installed dependancies.

I added the second line after `pip install -U setuptools`, and the docker build completed successfully.

If you want, I could go and revert the changes so I could get the error? I forgot to copy the error that came up.

**Comment by actionless** [comment]
could you remove `./scripts/env` directory and change here
https://github.com/superdesk/superdesk/blob/master/docker/requirements.txt
docker-compose version from 1.5.1 to 1.7.0?

in the original bug report i see what the issue marked resolved 28 days ago, mb updating docker-compose will do the trick (so it will depend on the newer docker-py version)

**Comment by timgws** [comment]
Yeah, I will try it in an hour or two.
