### ISSUE TITLE
Opening the local demo via ssh tunnel

### ISSUE THREAD

**Issue by andyfo** [superdesk/superdesk#2007]
Hi,

I am trying to run the local demo on my remote ubuntu server and serve the website through ssh tunnel with a different local port.

The tunnel is localhost:8900, so I changed 127.0.0.1 in the docker/common.yml file to this tunnel address.

I can open the superdesk login page but then I am getting 404 on the http://localhost:8900/api call when logging-in (I can see the request gets to the superdesk runner via the console log).

Are there some other settings I need to change for the tunnel to work? Thanks!

**Comment by actionless** [comment]
could you paste the response text from 404?
i need it to determine if that status was returned by api backend or container nginx

**Comment by zabojnik** [comment]
Response text:
`{"_error": {"code": 404, "message": "The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again."}, "_status": "ERR"}`

Log:
`superdesk_1 | 11:49:22 rest.1    | GET /api status=404 time=0s size=179b`

**Comment by actionless** [comment]
what are the values of those env vars:

```
   - SUPERDESK_URL
   - SUPERDESK_WS_URL
   - PUBLICAPI_URL
   - SUPERDESK_CLIENT_URL
```

**Comment by zabojnik** [comment]
From common.yml:
```
   - SUPERDESK_URL=http://localhost:8900/api
   - SUPERDESK_WS_URL=ws://localhost:8900/ws
   - PUBLICAPI_URL=http://localhost:8900/pubapi
   - SUPERDESK_CLIENT_URL=http://localhost:8900
```

**Comment by petrjasek** [comment]
looks like nginx config issue, we should use `$http_host` instead of `$host` in [nginx config](https://github.com/superdesk/superdesk/blob/master/docker/superdesk_vhost.conf#L30)

**Comment by actionless** [comment]
to me it looks more like this: https://github.com/pallets/werkzeug/pull/878

i am trying to include it now: https://github.com/superdesk/superdesk-core/pull/341

**Comment by petrjasek** [comment]
well `$host` doesn't include port, which is the problem for `localhost:8900`

**Comment by actionless** [comment]
@petrjasek submitted it as part of another PR:
https://github.com/superdesk/superdesk/pull/2009

**Comment by petrjasek** [comment]
cool lets see if that works
