### ISSUE TITLE
Api Returning 404

### ISSUE THREAD

**Issue by infralertsabp** [superdesk/superdesk#2511]
Hi,
I have installed superdesk as per the instruction given in the doc for docker images and my setup is on two servers i.e 
1. Running Apache as reverse proxy with the public ip address.
2. The complete stack of superdesk in docker.
Now my problem, When i change the given below entries in common.yml & docker-compose-prebuilt.yml from localhost to domain name all the api starts to return 404 :
- SUPERDESK_URL=http://superdesk.ttef.in/api
- PUBLICAPI_URL=http://superdesk.ttef.in/pubapi
- SUPERDESK_CLIENT_URL=http://superdesk.ttef.in

Can you please suggest what i am missing causing the issue.

**Comment by petrjasek** [comment]
hi, I think it could be that apache reverse proxy, it needs some equivalent of this nginx config:
https://github.com/superdesk/superdesk/blob/master/docker/superdesk_vhost.conf#L30

**Comment by infralertsabp** [comment]
Hello petrjasek,

Thanks for the update and the solution suggested by you worked. I have added "ProxyPreserveHost on" in virtual host which serves the superdesk.ttef.in and api started to return 200 response code but new problem has begin:

The given below urls are returning 4XX response codes and i am unable to login

- ws://superdesk.ttef.in/ws : returning 400 (Bad request)
- http://superdesk.ttef.in/api/ingest_providers?max_results=200 : 401 (UNAUTHORIZED)
- http://superdesk.ttef.in/api/backend_meta : 401 UNAUTHORIZED
- http://superdesk.ttef.in/api/auth : 401 UNAUTHORIZED

**Comment by petrjasek** [comment]
seems like admin user is not created or without the given password
