### ISSUE TITLE
[Question] Will the new custom fields feature be implemented in the sdsite branch of superdesk/superdesk?

### ISSUE THREAD

**Issue by nalyk** [superdesk/superdesk#2681]

**Comment by petrjasek** [comment]
it will get there, probably after cores 1.9 will be released

**Comment by nalyk** [comment]
Still no news? Is the sdsite branch still active? Is it another procedure/branch that can be installed along with Superdeesk Web Publisher?

**Comment by petrjasek** [comment]
it's not yet integrated on the publisher side so if there is a new custom field it wouldn't make it there.
needs some more work

**Comment by nalyk** [comment]
Thank you, waiting like mad. It would be a universal solution indeed.

**Comment by nalyk** [comment]
Just a bump. I know you did not forget, just can't wait to go forward with local dev.

**Comment by petrjasek** [comment]
@takeit any feedback on this?

**Comment by takeit** [comment]
hi, @nalyk

sdsite branch is not yet updated to the latest Superdesk version from master branch, thus the mentioned feature is not yet supported on the Publisher side. I have created a ticket and will include it in the upcoming sprints but there is no ETA yet on when it will be implemented. I will keep you informed about the progress here.

**Comment by nalyk** [comment]
Thank you, @petrjasek and @takeit. Your help is really appreciated here at UNIMEDIA. Thank you for your effort and your patience.
