### ISSUE TITLE
Locale must be set before running install

### ISSUE THREAD

**Issue by trondhuso** [superdesk/superdesk#2733]
Trying to setup super desk on a clean ubuntu-server. Third attempt...
curl -s https://raw.githubusercontent.com/superdesk/fireq/files/superdesk/install | sudo bash 
stoped when trying to set up virtual environment:

apt-get install python3-venv

This most likely because the server didn't have any locales set (yet). Setting up locales should either be described in the readme, or be added to the setup-script above.

T

**Comment by trondhuso** [comment]
Also adding these findings during install..
+ npm install
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated jquery@1.5.1: Versions of the jquery npm package older than 1.9.0 are patched versions that don't work in web browsers. Please upgrade to >=1.11.0.

**Comment by petrjasek** [comment]
thank you for report, what ubuntu server version is that?

**Comment by trondhuso** [comment]
pure clean 16.04
I would also recommend your install script does a check on resources before running installation. I tried on a server with only 1gb ram, and the installation stalled. Maybe also state this in the readme (minimum requirements and recommended requirements)

I also suggest the installation script installs postfix or sendmail e-mail server. Or that the readme points to a good postfix/sendmail installation tutorial.
