### ISSUE TITLE
Generating story/article automatically

### ISSUE THREAD

**Issue by trondhuso** [superdesk/superdesk#2750]
Hi is there a way for an external system to create a new article with slug, title/headline and so on?
if so ... how?

**Comment by petrjasek** [comment]
that could work via ingest, but would involve creating some files or provide rss, there is no http api yet

**Comment by trondhuso** [comment]
So like an NITF more or less empty except for headline and so on?

 

Like this:

 

<?xml version="1.0" encoding="utf-8"?>
<nitf version="-//IPTC//DTD NITF 3.6//EN">
    <head>
        <title>A test message</title>
        <docdata>
            <doc-id regsrc="customer" id-string="abcdefg-12345678"/>
            <date.issue norm="20171201T155000Z"/>
            <doc.copyright holder="Customer" year="2017"/>
            <du-key version="1" key="key-test-message"/>
        </docdata>
    </head>
    <body>
        <body.head>
            <hedline>
                <hl1 id="headline">A test message</hl1>
            </hedline>
            <distributor>The Customer</distributor>
        </body.head>
        <body.content>
        </body.content>
    </body>
</nitf>

 

 

Trond Husø

 

Fra: Petr Jašek [mailto:notifications@github.com] 
Sendt: Friday, December 1, 2017 2:43 PM
Til: superdesk/superdesk <superdesk@noreply.github.com>
Kopi: Trond Husø <trond@trondhuso.no>; Author <author@noreply.github.com>
Emne: Re: [superdesk/superdesk] Generating story/article automatically (#2750)

 

that could work via ingest, but would involve creating some files or provide rss, there is no http api yet

**Comment by petrjasek** [comment]
yes something like that

**Comment by trondhuso** [comment]
Closing as the answer solves the issue.

the NITF below is a bare minimum to ingest an NITF XML document into Superdesk:

```
<?xml version=“1.0” encoding=“UTF-8"?>
<nitf>
  <head>
    <title>Superdesk Ingest Test</title>
    <docdata>
      <doc-id regsrc=“SCRPE” id-string=“cedd5bfb-9b10-4c31-b2f9-2e740309b618-3"/>
      <date.issue norm=“20180629T040619+0200”/>
      <doc.copyright holder=“SCRPE” year=“2018”/>
      <du-key version=“0" key=“slug-test-ingest”/>
      <evloc city=“Oslo” iso-cc=“NOR” />
    </docdata>
  </head>
  <body>
    <body.head>
      <hedline>
        <hl1>Superdesk Ingest Test</hl1>
      </hedline>
    </body.head>
    <body.content>
      <p lede=“true”>This is a Superdesk Ingest Test.</p>
      <p>This document is an ingest test to see if the document is being ingested or not.</p>
    </body.content>
  </body>
</nitf>
```
