### ISSUE TITLE
Pulling in new data

### ISSUE THREAD

**Issue by trondhuso** [superdesk/superdesk#2751]
Hi,

I have a json file with dateline-information (places), how do I import this list?

**Comment by petrjasek** [comment]
hi,

you can put the file somewhere in server folder and set path to it in settings.py:
```
LOCATORS_DATA_FILE = 'path/to/file'
```

**Comment by trondhuso** [comment]
I have also done this:

`python3 manage.py app:initialize_data -p ./data/ -f`

**Note: Remember I am referencing the folder, not the file. So, any file in that folder will be initialized.**

As soon as I get a test environment up, I will test the settings.py solution as well.

The layout of the locators.json-file was like this:

```
[
    {
        "qcode":"IL",
        "name": "Israel",
        "state": [
            {"name": "Golan Heights Region", "qcode": "GOHR", "world_region": "Middle East"},
            {"name": "Upper Galilee Region", "qcode": "UPGR", "world_region": "Middle East"},
```
