### ISSUE TITLE
Issue remains - docker-compose

### ISSUE THREAD

**Issue by DarkBlaez** [superdesk/superdesk#2762]
Originally saw this issue posted but never resolved since others hyjacked the original issue with layering on their own in the thread.

Original issue per: ./scripts/docker-local-demo.sh  so essentially

docker-compose -f docker/docker-compose-prebuilt.yml up

Everything starts just fine, no issues. The only issue is with superdesk connecting to mongodb

superdesk_1  | waiting for mongo on mongodb:27017 ...
mongodb_1    | 2017-12-11T20:47:48.271+0000 I NETWORK  [listener] connection accepted from 172.17.0.6:42392 #57 (1 connection now open)

This repeats endlessly until superdesk times out. This issue is repeatabe everytime. Spin up a new VM (pick any Linus OS you prefer) install docker & docker-compose. git clone the repos as per the instructions. Attempt to launch per the script or docker-compose

End result is the same every time, endlessly waiting for mongodb. Change docker-compose to expose the port or even enter IP. Result is the same. Superdesk is not connecting as far as can be determined based on the limited output.

This has existed for a while. When will this be addressed. The response of trying to do a manual install or external to docker will not address this and would circumvent the issue. Just want to head that response off.

Thoughts? Solution?

Thanks in advance
DB

**Comment by petrjasek** [comment]
hi @DarkBlaez I think https://github.com/superdesk/superdesk/pull/2763 should fix it, can you give it a try?
