### ISSUE TITLE
 where to set  environment of superdesk?

### ISSUE THREAD

**Issue by cn3c3p** [superdesk/superdesk#2834]
I use  docke-rmongodb3.4, need authenticate to this database.
To authenticate after connecting  docke-rmongodb3.4  ,where to set  environment:  
MONGO_INITDB_ROOT_USERNAME: root  
MONGO_INITDB_ROOT_PASSWORD: root.123  ?

**Comment by petrjasek** [comment]
you should set `MONGO_URI` env var, you can put it to `server/.env` for example
