### ISSUE TITLE
TypeError: 'encoding' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by jvkiran** [superdesk/superdesk#2868]
Downloading/unpacking websockets>=3.0,<4.1 (from Superdesk-Core->-r requirements.txt (line 5))
  Downloading websockets-4.0.1.tar.gz (61kB): 61kB downloaded
  Running setup.py (path:/tmp/pip_build_gtcoder/websockets/setup.py) egg_info for package websockets
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_gtcoder/websockets/setup.py", line 11, in <module>
        with open(readme_file, encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_gtcoder/websockets/setup.py", line 11, in <module>

    with open(readme_file, encoding='utf-8') as f:

Above error occured, while running this command  "pip install -r requirements.txt"

**Comment by petrjasek** [comment]
hi, what python/pip version is that?

**Comment by jvkiran** [comment]
It's Python 2.7.6

**Comment by jvkiran** [comment]
Yes, it's working now.
