### ISSUE TITLE
Create site wizard is not working in localhost

### ISSUE THREAD

**Issue by jvkiran** [superdesk/superdesk#2873]
Below are console errors:

OPTIONS https://localhost/api/v1/auth/superdesk/ net::ERR_CONNECTION_REFUSED
OPTIONS https://localhost/api/v1/organization/themes/ net::ERR_CONNECTION_REFUSED
OPTIONS https://localhost/api/v1/tenants/ net::ERR_CONNECTION_REFUSED

**Comment by petrjasek** [comment]
@takeit any idea?

**Comment by takeit** [comment]
@tomaszrondio could you follow up on it, please?

**Comment by tomaszrondio** [comment]
well, not really as I don't have superdesk publisher locally. I guess it is something with backend configuration.

**Comment by jvkiran** [comment]
I've included port and getting response in below

http://0.0.0.0:5000/api/v1/auth/superdesk


{"_status": "ERR", "_error": {"code": 404, "message": "The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again."}}

**Comment by jvkiran** [comment]
solved, thanks.
