### ISSUE TITLE
Which repo shall i install superdesk(angular & python) or web-publisher(symfony) in production server as a user

### ISSUE THREAD

**Issue by jvkiran** [superdesk/superdesk#2877]
Please clear my confusion.

**Comment by petrjasek** [comment]
hi, you have to always install angular/python in order to produce content, if you also want it to render a website you need web-publisher

**Comment by jvkiran** [comment]
But there is also a publisher in superdesk, which contains output control and output settings etc.

**Comment by jvkiran** [comment]
Hi,
I have little more clarity now. We have installed Superdesk along with the publisher 'component'. Once we complete 'Output Settings' like domain name etc, we can push the content. Then we don't need the php-based web-publisher, right? And if we have to push content to a wordpress site, we can use the 'wordpress plugin' and we don't need the 'component', am I right?

**Comment by petrjasek** [comment]
yes exactly

**Comment by jvkiran** [comment]
Thanks
