### ISSUE TITLE
500 error, while fetching article from working desk 

### ISSUE THREAD

**Issue by jvkiran** [superdesk/superdesk#2881]
Below is the log

17:25:55 rest.1 | [2018-05-17 17:25:55,074] ERROR in app: Exception on /api/archive [GET]
17:25:55 rest.1 | Traceback (most recent call last):
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
17:25:55 rest.1 |     response = self.full_dispatch_request()
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
17:25:55 rest.1 |     rv = self.handle_user_exception(e)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
17:25:55 rest.1 |     reraise(exc_type, exc_value, tb)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
17:25:55 rest.1 |     raise value
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
17:25:55 rest.1 |     rv = self.dispatch_request()
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
17:25:55 rest.1 |     return self.view_functions[rule.endpoint](**req.view_args)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/eve/endpoints.py", line 54, in collections_endpoint
17:25:55 rest.1 |     response = get(resource, lookup)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/eve/methods/common.py", line 284, in rate_limited
17:25:55 rest.1 |     return f(*args, **kwargs)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/eve/auth.py", line 79, in decorated
17:25:55 rest.1 |     return f(*args, **kwargs)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/eve/methods/common.py", line 1040, in decorated
17:25:55 rest.1 |     r = f(resource, **combined_args)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/eve/methods/get.py", line 39, in get
17:25:55 rest.1 |     return get_internal(resource, **lookup)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/eve/methods/get.py", line 112, in get_internal
17:25:55 rest.1 |     return _perform_find(resource, lookup)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/eve/methods/get.py", line 184, in _perform_find
17:25:55 rest.1 |     cursor = app.data.find(resource, req, lookup)
17:25:55 rest.1 |   File "/home/gtcoder/Sites/superdesk/server/src/superdesk-core/superdesk/datalayer.py", line 57, in find
17:25:55 rest.1 |     return superdesk.get_resource_service(resource).get(req=req, lookup=lookup)
17:25:55 rest.1 |   File "/home/gtcoder/Sites/superdesk/server/src/superdesk-core/superdesk/services.py", line 98, in get
17:25:55 rest.1 |     return self.backend.get(self.datasource, req=req, lookup=lookup)
17:25:55 rest.1 |   File "/home/gtcoder/Sites/superdesk/server/src/superdesk-core/superdesk/eve_backend.py", line 89, in get
17:25:55 rest.1 |     cursor = backend.find(endpoint_name, req, lookup)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/eve_elastic/elastic.py", line 495, in find
17:25:55 rest.1 |     hits = self.elastic(resource).search(body=query, **args)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
17:25:55 rest.1 |     return func(*args, params=params, **kwargs)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 539, in search
17:25:55 rest.1 |     doc_type, '_search'), params=params, body=body)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/elasticsearch/transport.py", line 327, in perform_request
17:25:55 rest.1 |     status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 110, in perform_request
17:25:55 rest.1 |     self._raise_error(response.status, raw_data)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 114, in _raise_error
17:25:55 rest.1 |     raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
17:25:55 rest.1 | elasticsearch.exceptions.RequestError: TransportError(400, 'parsing_exception', 'no [query] registered for [filtered]')
17:25:55 rest.1 | ERROR:superdesk.errors:HTTP Exception 500 has been raised: TransportError(400, 'parsing_exception', 'no [query] registered for [filtered]')
17:25:55 rest.1 | [2018-05-17 17:25:55 +0530] [6185] [ERROR] Error handling request /api/archive?auto=0&es_highlight=0&projections=[%22highlights%22,%22_created%22,%22_updated%22,%22_etag%22,%22_type%22,%22state%22,%22embargo%22,%22publish_schedule%22,%22broadcast%22,%22flags%22,%22rewrite_of%22,%22rewritten_by%22,%22expiry%22,%22task%22,%22type%22,%22linked_in_packages%22,%22renditions%22,%22item_id%22,%22guid%22,%22_current_version%22,%22lock_user%22,%22lock_session%22,%22genre%22,%22source%22,%22language%22,%22last_published_version%22,%22archived%22,%22associations%22,%22queue_state%22,%22alt_text%22,%22description_text%22,%22assignment_id%22,%22byline%22,%22copyrightholder%22,%22copyrightnotice%22,%22usageterms%22,%22priority%22,%22urgency%22,%22word_count%22,%22slugline%22,%22marked_desks%22,%22headline%22,%22versioncreated%22,%22profile%22,%22correction_sequence%22,%22anpa_take_key%22,%22signal%22,%22anpa_category%22,%22ingest_provider%22]&source={%22query%22:{%22filtered%22:{%22filter%22:{%22and%22:[{%22not%22:{%22term%22:{%22state%22:%22spiked%22}}},{%22or%22:[{%22and%22:[{%22term%22:{%22state%22:%22draft%22}},{%22term%22:{%22original_creator%22:%225ae6f3a138204840ab46b921%22}}]},{%22not%22:{%22terms%22:{%22state%22:[%22draft%22]}}}]},{%22not%22:{%22term%22:{%22package_type%22:%22takes%22}}},{%22term%22:{%22task.stage%22:%225ae6f3bf38204840d4b98b73%22}}]}}},%22sort%22:[{%22versioncreated%22:%22desc%22}],%22from%22:0,%22size%22:25}
17:25:55 rest.1 | Traceback (most recent call last):
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
17:25:55 rest.1 |     response = self.full_dispatch_request()
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
17:25:55 rest.1 |     rv = self.handle_user_exception(e)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
17:25:55 rest.1 |     reraise(exc_type, exc_value, tb)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
17:25:55 rest.1 |     raise value
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
17:25:55 rest.1 |     rv = self.dispatch_request()
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
17:25:55 rest.1 |     return self.view_functions[rule.endpoint](**req.view_args)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/eve/endpoints.py", line 54, in collections_endpoint
17:25:55 rest.1 |     response = get(resource, lookup)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/eve/methods/common.py", line 284, in rate_limited
17:25:55 rest.1 |     return f(*args, **kwargs)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/eve/auth.py", line 79, in decorated
17:25:55 rest.1 |     return f(*args, **kwargs)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/eve/methods/common.py", line 1040, in decorated
17:25:55 rest.1 |     r = f(resource, **combined_args)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/eve/methods/get.py", line 39, in get
17:25:55 rest.1 |     return get_internal(resource, **lookup)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/eve/methods/get.py", line 112, in get_internal
17:25:55 rest.1 |     return _perform_find(resource, lookup)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/eve/methods/get.py", line 184, in _perform_find
17:25:55 rest.1 |     cursor = app.data.find(resource, req, lookup)
17:25:55 rest.1 |   File "/home/gtcoder/Sites/superdesk/server/src/superdesk-core/superdesk/datalayer.py", line 57, in find
17:25:55 rest.1 |     return superdesk.get_resource_service(resource).get(req=req, lookup=lookup)
17:25:55 rest.1 |   File "/home/gtcoder/Sites/superdesk/server/src/superdesk-core/superdesk/services.py", line 98, in get
17:25:55 rest.1 |     return self.backend.get(self.datasource, req=req, lookup=lookup)
17:25:55 rest.1 |   File "/home/gtcoder/Sites/superdesk/server/src/superdesk-core/superdesk/eve_backend.py", line 89, in get
17:25:55 rest.1 |     cursor = backend.find(endpoint_name, req, lookup)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/eve_elastic/elastic.py", line 495, in find
17:25:55 rest.1 |     hits = self.elastic(resource).search(body=query, **args)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
17:25:55 rest.1 |     return func(*args, params=params, **kwargs)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 539, in search
17:25:55 rest.1 |     doc_type, '_search'), params=params, body=body)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/elasticsearch/transport.py", line 327, in perform_request
17:25:55 rest.1 |     status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 110, in perform_request
17:25:55 rest.1 |     self._raise_error(response.status, raw_data)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 114, in _raise_error
17:25:55 rest.1 |     raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
17:25:55 rest.1 | elasticsearch.exceptions.RequestError: TransportError(400, 'parsing_exception', 'no [query] registered for [filtered]')
17:25:55 rest.1 | 
17:25:55 rest.1 | During handling of the above exception, another exception occurred:
17:25:55 rest.1 | 
17:25:55 rest.1 | Traceback (most recent call last):
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
17:25:55 rest.1 |     self.handle_request(listener, req, client, addr)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
17:25:55 rest.1 |     respiter = self.wsgi(environ, resp.start_response)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/eve/flaskapp.py", line 1033, in __call__
17:25:55 rest.1 |     return super(Eve, self).__call__(environ, start_response)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
17:25:55 rest.1 |     return self.wsgi_app(environ, start_response)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
17:25:55 rest.1 |     response = self.handle_exception(e)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1547, in handle_exception
17:25:55 rest.1 |     return self.finalize_request(handler(e), from_error_handler=True)
17:25:55 rest.1 |   File "/home/gtcoder/Sites/superdesk/server/src/superdesk-core/superdesk/factory/app.py", line 136, in server_error_handler
17:25:55 rest.1 |     return client_error_handler(return_error)
17:25:55 rest.1 |   File "/home/gtcoder/Sites/superdesk/server/src/superdesk-core/superdesk/factory/app.py", line 126, in client_error_handler
17:25:55 rest.1 |     return send_response(None, (error.to_dict(), None, None, error.status_code))
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/eve/render.py", line 57, in decorated
17:25:55 rest.1 |     r = f(*args, **kwargs)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/eve/render.py", line 96, in send_response
17:25:55 rest.1 |     return _prepare_response(resource, *response if response else [None])
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/eve/render.py", line 150, in _prepare_response
17:25:55 rest.1 |     rendered = globals()[renderer](dct)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/eve/render.py", line 303, in render_json
17:25:55 rest.1 |     sort_keys=config.JSON_SORT_KEYS)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/simplejson/__init__.py", line 399, in dumps
17:25:55 rest.1 |     **kw).encode(obj)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/simplejson/encoder.py", line 286, in encode
17:25:55 rest.1 |     chunks = self.iterencode(o, _one_shot=True)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/simplejson/encoder.py", line 368, in iterencode
17:25:55 rest.1 |     return _iterencode(o, 0)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/eve/io/mongo/mongo.py", line 57, in default
17:25:55 rest.1 |     return super(MongoJSONEncoder, self).default(obj)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/eve/io/base.py", line 36, in default
17:25:55 rest.1 |     return json.JSONEncoder.default(self, obj)
17:25:55 rest.1 |   File "/usr/local/lib/python3.6/site-packages/simplejson/encoder.py", line 263, in default
17:25:55 rest.1 |     o.__class__.__name__)
17:25:55 rest.1 | TypeError: Object of type RequestError is not JSON serializable
17:25:55 rest.1 | GET None status=500 time=0s size=0b

**Comment by petrjasek** [comment]
looks like some incompatible elastic version, we only support 1.7-2.4 atm

**Comment by jvkiran** [comment]
Fixed, Thanks.
