### ISSUE TITLE
404 error, while creating tenants (Create site wizard) - publisher

### ISSUE THREAD

**Issue by jvkiran** [superdesk/superdesk#2882]
Request URL:
http://localhost:9000/api/v1/tenants/

Response body:
{"tenant":{"name":"cardlove","domainName":"http://cardlove.co.in"}}

Server response:
code | 404
message | The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

**Comment by petrjasek** [comment]
hi, pls add the issue to https://github.com/superdesk/superdesk-publisher

**Comment by jvkiran** [comment]
Hi, I've a doubt.

superdesk-publisher is just a client,
but above issue is related to server, so this the correct repo right?

**Comment by petrjasek** [comment]
ah right, that should go to https://github.com/superdesk/web-publisher then
