### ISSUE TITLE
Username could not be found.

### ISSUE THREAD

**Issue by jvkiran** [superdesk/superdesk#2887]
http://139.162.61.246/api/v1/organization/themes/

{"status":403,"message":"Username could not be found."}

Which username and domain should i add, in manual it says "that points to publisher instance".

i've installed superdesk and wep-publisher in different server.

Please help

**Comment by petrjasek** [comment]
ping @superdesk/superdesk-publishing

**Comment by jvkiran** [comment]
Hi,
Result after pinging 
ping: unknown host @superdesk/superdesk-publishing
