### ISSUE TITLE
Local File Feed ingest acts very glitchy and cannot load feed parsers on fresh install on Ubuntu 16.04

### ISSUE THREAD

**Issue by CaerphillyMediaLtd** [superdesk/superdesk#2888]
Hi,

I've followed the installation instructions using the single line install on a fresh installation of Ubuntu 16.04. I've tried setting up some RSS feed ingests and they work perfectly, but when I try to setup a local folder to be monitored it never ingests them into Superdesk correctly.

I've set it to monitor a local folder and update every minute and have set the feed parser to News ML 2.0 Parser (I've also tried NINJS, Scoop Media... etc, they all give the same errors). It correctly creates _ERROR and _PROCESSED in this folder. I've then added some example News ML 2.0 (or NINJS) examples from here:

https://www.iptc.org/std/NewsML-G2/2.24/examples/

But the first time it tries to parse a file in the folder I get a log email:

System Error [1002] on ingest provider test123: SuperdeskIngestError Error 2000 - Configured Feed Parser either not found or not registered with the application

As far as I know all of the configuration feed parsers are being registered (I just added a little python to the register method to verify this). Despite this some of the files like the following:

https://www.iptc.org/std/NewsML-G2/2.24/examples/LISTING%2013%20Complete%20Catalog%20Item.xml

Go into the _PROCESSED folder but nothing shows up in Superdesk. Many other valid example files also go into _ERROR (even the simplest NewsML file goes into _ERROR most of the time).

Is this a bug? I've tried reinstalling Superdesk on a fresh copy of Ubuntu 16.04 and I still get the exact same issue?

**Comment by CaerphillyMediaLtd** [comment]
Here's a bit of a more minimal example using the ninjs example:

{
    "uri" : "http://ninjs.example.com/newsitems/test",
    "type" : "text",
    "versioncreated" : "2018:05:22T15:37:00Z",
    "byline" : "abc",
    "headline" : "def",
    "body_text" : "hij"
}

That's valid and it gets put into the _PROCESSED folder. But on Superdesk there's nothing there when I go to the ingest items (and make sure there's no filter on).

**Comment by CaerphillyMediaLtd** [comment]
I just found the problems.

The NINJS examples don't contain a GUID. The parser doesn't care about this and parses it correctly and puts it into the _PROCESSED folder, but it's not added to Superdesk . The error is in the log file but it's not at all descriptive (it's just a python exception). To comply with the standard would it not be better to maybe generate a GUID? Or at least log a better error.

newsml_2_0.py is described in Superdesk as if it conforms to the NewsML-G2 standard. It's not mentioned in the source that it's only designed for AP's specific implementation, I only found out from the commit comment. I couldn't find any parser which is built to follow the actual standard. In regards to Error 2000, it seems it's getting thrown invalidly as the parser is still running?

**Comment by petrjasek** [comment]
hi, can you pls attach the log with error? that `newsml_2_0` is not designed to work with ap only, it should work in general but we were only testing feeds we were using so far (ap, reuters).

**Comment by CaerphillyMediaLtd** [comment]
[sd.log](https://github.com/superdesk/superdesk/files/2031504/sd.log)

In regards to the NewsML implementation, it should be done to the [official IPTC spec](https://iptc.org/standards/newsml-g2/using-newsml-g2/). It gives up on many valid items straight away as can_parse only checks if the document ends with newsMessage, if you take a look at the XML schema [here](https://www.iptc.org/std/NewsML-G2/2.15/specification/NewsML-G2_2.15-spec-All-Power.xsd) there's many different tags that are considered valid. In the IPTC examples I linked to in the first post they pretty much all get eliminated as few (none?) of them end with newsMessage, the more typical standard tag to use is newsItem.

I'm assuming the NINJS standard hasn't been implemented from the IPTC spec either? I've just tried implementing the BBC's LDRS, and have tried using different example test files and they often throw an error because the parser doesn't like dates formated like "2018-05-22T16:10:34".

I've also had a bug where sometimes the parsers stop checking for several minutes (I think after an error? But it might be confirmation bias), restarting the service doesn't work, what usually works for me is disabling one of them then re-enabling it? Do you have any idea what might be causing that?

**Comment by CaerphillyMediaLtd** [comment]
Also here's another bug with the NINJS parser, at line 88 you have:

    if ninjs.get('associations', {}).get('featuremedia'):

Which is particularly problematic because associations can often be an array, so ninjs.get('associations', {}) returns a list instead of a dictionary, and there's no 'get' method for a list. For example the following is a real example (actually has 5 associations but I reduced it to post it):

    "associations": [
      {
        "id": "featureimage",
        "headline": "IMG_1346.JPG",
        "description_text": "redacted",
        "type": "picture",
        "renditions": {
          "original": {
            "href": "redacted",
            "mimetype": "image/jpeg",
            "filename": "IMG_1346.JPG",
            "width": "3264",
            "height": "2448"
          }
        }
      },
      {
        "id": "0_ru0aaque",
        "headline": "IMG_1349.JPG",
        "description_text": "redacted",
        "type": "image",
        "renditions": {
          "original": {
            "href": "redacted",
            "mimetype": "image/jpeg",
            "filename": "IMG_1349.JPG",
            "width": "3264",
            "height": "2448"
          }
        }
      },
      ...
    ]

**Comment by petrjasek** [comment]
are you sure associations can be an array? according to [schema](http://www.iptc.org/std/ninjs/ninjs-schema_1.1.json) it's type object

**Comment by CaerphillyMediaLtd** [comment]
Apologies, it looks like the BBC have strayed from the correct Schema.

**Comment by petrjasek** [comment]
yep will check that
