### ISSUE TITLE
Authorization is not working with publisher

### ISSUE THREAD

**Issue by jvkiran** [superdesk/superdesk#2893]
While creating tenant from output setting following error appeared.
POST http://139.162.61.246/api/v1/auth/superdesk

Request Body:
{"auth_superdesk":{"session_id":"5b06a58e421aa91aa6419d65","token":"Basic OTA4YWQ1M2MtMzVkZi00MjliLWI4MGMtNThlNTZmMmQ3ZjdiOg=="}}

**Request Headers:**
Host: 139.162.61.246
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: application/json, text/plain, */*
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://172.104.43.88/
Authorization: **Basic undefined**
Content-Type: application/json;charset=utf-8
Content-Length: 129
Origin: http://172.104.43.88
Connection: keep-alive

**Response Headers:**
HTTP/1.1 500 Internal Server Error
Server: nginx/1.10.3 (Ubuntu)
Date: Thu, 24 May 2018 07:55:34 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive

**Comment by petrjasek** [comment]
cc @superdesk/superdesk-publishing

**Comment by felixovelar** [comment]
> While creating tenant from output setting following error appeared.
> POST http://139.162.61.246/api/v1/auth/superdesk
> 
> Request Body:
> {"auth_superdesk":{"session_id":"5b06a58e421aa91aa6419d65","token":"Basic OTA4YWQ1M2MtMzVkZi00MjliLWI4MGMtNThlNTZmMmQ3ZjdiOg=="}}
> 
> **Request Headers:**
> Host: 139.162.61.246
> User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
> Accept: application/json, text/plain, _/_
> Accept-Language: en-GB,en;q=0.5
> Accept-Encoding: gzip, deflate
> Referer: http://172.104.43.88/
> Authorization: **Basic undefined**
> Content-Type: application/json;charset=utf-8
> Content-Length: 129
> Origin: http://172.104.43.88
> Connection: keep-alive
> 
> **Response Headers:**
> HTTP/1.1 500 Internal Server Error
> Server: nginx/1.10.3 (Ubuntu)
> Date: Thu, 24 May 2018 07:55:34 GMT
> Content-Type: text/html; charset=UTF-8
> Transfer-Encoding: chunked
> Connection: keep-alive

Hello @jvkiran 
How did you fix the problem with "undefined" on the Authorization header?
I'm having the same issue. The Token is ok on the payload but not on the header and I get 401 Unauthorized.
I will appreciate any help!
Thanks
