### ISSUE TITLE
Authorization error to access contentapi

### ISSUE THREAD

**Issue by jvkiran** [superdesk/superdesk#2898]
http://172.104.43.88/contentapi, while access asking username and password.
401 UNAUTHORIZED

Respose payload:
{"_status": "ERR", "_error": {"message": "Please provide proper credentials", "code": 401}}

What are the credentials to login or how do i create one?
Need help.

**Comment by petrjasek** [comment]
you go to settings/subscribers, edit subscriber and there is tab with content api tokens, you should generate one and use it as username or via authorization header

**Comment by jvkiran** [comment]
@petrjasek  Great, I got it working.
