### ISSUE TITLE
Planning and Analytics menu in superdesk

### ISSUE THREAD

**Issue by jvkiran** [superdesk/superdesk#2923]
I can't see planning and analytics menu in superdesk, after following installation instructions from respective repo's.

There are no errors in the log as well.

**Comment by petrjasek** [comment]
there is a switch in client config to allow the planning:
https://github.com/superdesk/superdesk/blob/planning-mvp/client/superdesk.config.js#L47-L50

**Comment by petrjasek** [comment]
and you have to add it to apps there
https://github.com/superdesk/superdesk/blob/planning-mvp/client/superdesk.config.js#L9

**Comment by petrjasek** [comment]
same for analytics:
https://github.com/superdesk/superdesk/blob/master/client/superdesk.config.js#L61-L63
