### ISSUE TITLE
Superdesk transforms Publisher name without subdomain to "null.domain.com"

### ISSUE THREAD

**Issue by ioncebotari** [superdesk/superdesk#2988]
When clicking on Publisher -> Output settings -> Open for a Publisher instance, instead of expected URI http://localkyht.com I get the URI http://null.localkyht.com. Please see the attached screenshot to confirm that.
![screenshot_20181111_203648](https://user-images.githubusercontent.com/3043499/48316861-9edd9180-e5f1-11e8-80f9-32e20e03b7bf.png)

**Comment by petrjasek** [comment]
ping @takeit

**Comment by shivharis** [comment]
A similar issue happens when uploading logo files. However, the errors show up in Chrome console; the image uploaded shows up as a broken image icon. Also, not logo is uploaded.

**Comment by shivharis** [comment]
> UI bug. It is fixed in upcoming release.
Do you mean the master branch?
