### ISSUE TITLE
Save button not highlighted

### ISSUE THREAD

**Issue by shivharis** [superdesk/superdesk#2990]
When a website is updated in page Manage: website and then reset to "Theme Defaults", Save button should be highlighted to make sure the updating is possible. Hence not possible to revert to "Theme Defaults"

**Comment by shivharis** [comment]
On closer examination, it appears that the 'theme defaults' are automatically applied without the need for a separate 'save' button click. Is that what is required/correct?

**Comment by tomaszrondio** [comment]
correct. Theme defaults are reverted without need to click save button.

**Comment by shivharis** [comment]
Closing issue accepted tomaszrondio's comment
