### ISSUE TITLE
wss://null.<domainname> Or wss://null.<ip address>

### ISSUE THREAD

**Issue by shivharis** [superdesk/superdesk#2996]
(edited to show text swallowed by encoding)

Using '(' instead of '<'

The new release seems to have some issues fixed regarding null.(ip address) or null.(domainname).

However, has introduced similar new issues elsewhere. Particularly with protocol
wss://null.<ip/dom>. making it impossible to publish to a website.

Overall it would be nice if URI construction of such uses the config.xxx.js file and use of 'wss' or 'ws' is configurable from that file. The code uses wsDomain but that's about it. it does not seem to use wsProtocol.

**Comment by shivharis** [comment]
I had also sent out a pull request, please use it for whatever it is worth:

https://github.com/superdesk/superdesk-publisher/pull/74

**Comment by takeit** [comment]
fixed in https://github.com/superdesk/superdesk-publisher/pull/78
