### ISSUE TITLE
lost the website management button (or whatever the new name is)

### ISSUE THREAD

**Issue by shivharis** [superdesk/superdesk#2997]
Even if there are no websites configured (empty config.xxxx.js) , you will still need access to the website management page to at least reach the "+" button to add the very first website. This situation occurs when there are not apps in client/dists/config.xxxxx.js

**Comment by tomaszrondio** [comment]
in config.xxxx.js there is publisher instance configuration. You need this to create websites. It is impossible to create first website without telling where publisher instance and its API is.

**Comment by shivharis** [comment]
Maybe the existence of the config.xxx.js file, not its contents, should allow access to the "+" button.
