### ISSUE TITLE
upload logo for theme customization not functional

### ISSUE THREAD

**Issue by shivharis** [superdesk/superdesk#2998]
Cannot upload a logo. uri still has "null" in it.

**Comment by petrjasek** [comment]
@takeit is it publisher?

**Comment by takeit** [comment]
@petrjasek yes

/cc @tomaszrondio

**Comment by tomaszrondio** [comment]
please check console if there are any errors from logo upload.

**Comment by shivharis** [comment]
console error:

GET https://null.192.168.15.40/theme_logo/86/7d/e87ce15….png net::ERR_NAME_NOT_RESOLVED

apologies, my very first comment was too terse.

**Comment by tomaszrondio** [comment]
thanks, that is helpful. We will have a look at this and let you know asap.

**Comment by shivharis** [comment]
thanks

**Comment by shivharis** [comment]
Please refer to pull request in superdesk/superdesk-publisher for possible fix.

https://github.com/superdesk/superdesk-publisher/pull/77

**Comment by takeit** [comment]
fixed by https://github.com/superdesk/superdesk-publisher/pull/77
