### ISSUE TITLE
Solution to resolve SuperDesk (Pillow) on MacOS Catalina

### ISSUE THREAD

**Issue by 2gavy** [superdesk/superdesk#3138]
![Screenshot 2020-01-18 at 5 13 38 PM](https://user-images.githubusercontent.com/9292451/72661506-df1a7a00-3a15-11ea-9cd6-cfb417f369c3.png)

Had some troubles installing SuperDesk on MacOS Catalina. After some digging on Pillow github issue page, found that the [solution](https://github.com/python-pillow/Pillow/issues/3438#issuecomment-543812237) was to:

`export CPATH=xcrun --show-sdk-path/usr/include`

Hope this will help someone in the future. :)

**Comment by sagun786** [comment]
I am facing the same issue. I have tried trick in the book.  

Saguns-MacBook-Pro:server sagungargs$ pip3 install -r requirements.txt
Requirement already satisfied: gunicorn==19.7.1 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (19.7.1)
Requirement already satisfied: honcho==1.0.1 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (1.0.1)
Requirement already satisfied: newrelic<2.67,>=2.66 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages/newrelic-2.66.0.49 (from -r requirements.txt (line 3)) (2.66.0.49)
Obtaining superdesk-core from git+git://github.com/superdesk/superdesk-core.git@develop#egg=superdesk-core (from -r requirements.txt (line 5))
  Updating /Users/sagungargs/pyvenv/src/superdesk-core clone (to revision develop)
  Running command git fetch -q --tags
  Running command git reset --hard -q 6d5292437111566eac683ab99772727dbfae5767
Obtaining superdesk-analytics from git+git://github.com/superdesk/superdesk-analytics.git@master#egg=superdesk-analytics (from -r requirements.txt (line 6))
  Updating /Users/sagungargs/pyvenv/src/superdesk-analytics clone (to revision master)
  Running command git fetch -q --tags
  Running command git reset --hard -q b4a944f2031cec1ff958dc486cbd1850e8a5fcc4
Requirement already satisfied: eve<=0.7.8,>=0.6 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from superdesk-core->-r requirements.txt (line 5)) (0.7.8)
Requirement already satisfied: eve-elastic==2.5.0 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from superdesk-core->-r requirements.txt (line 5)) (2.5.0)
Requirement already satisfied: flask<=0.12,>=0.10.1 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from superdesk-core->-r requirements.txt (line 5)) (0.12)
Requirement already satisfied: flask-oauthlib<0.10,>=0.9.3 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from superdesk-core->-r requirements.txt (line 5)) (0.9.5)
Requirement already satisfied: flask-mail<0.10,>=0.9 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from superdesk-core->-r requirements.txt (line 5)) (0.9.1)
Requirement already satisfied: flask-script<3.0,>=2.0.5 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from superdesk-core->-r requirements.txt (line 5)) (2.0.6)
Requirement already satisfied: flask_pymongo<1.0,>=0.5.2 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from superdesk-core->-r requirements.txt (line 5)) (0.5.2)
Requirement already satisfied: flask-babel==0.12.2 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from superdesk-core->-r requirements.txt (line 5)) (0.12.2)
	Collecting pillow<=5.0,>=3.0
  Using cached Pillow-5.0.0.tar.gz (14.2 MB)
Requirement already satisfied: arrow<=0.13,>=0.4 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from superdesk-core->-r requirements.txt (line 5)) (0.13.0)
Collecting asyncio<3.5,>=3.4
  Using cached asyncio-3.4.3-py3-none-any.whl (101 kB)
Collecting bcrypt<3.2,>=3.1.1
  Using cached bcrypt-3.1.7-cp34-abi3-macosx_10_6_intel.whl (53 kB)
Requirement already satisfied: blinker<1.5,>=1.3 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from superdesk-core->-r requirements.txt (line 5)) (1.4)
Collecting celery[redis]<4.4,>=4.3.0
  Using cached celery-4.3.0-py2.py3-none-any.whl (413 kB)
Collecting redis<3.3,>=3.2.0
  Using cached redis-3.2.1-py2.py3-none-any.whl (65 kB)
Collecting kombu<4.6,>=4.5
  Using cached kombu-4.5.0-py2.py3-none-any.whl (185 kB)
Processing /Users/sagungargs/Library/Caches/pip/wheels/4a/87/a9/ef99b7b68f9816d5ef1262dc11ce31a93a844eb69e68c1a031/feedparser-5.2.1-py3-none-any.whl
Collecting hachoir<=3.0a3
  Using cached hachoir-3.0a3-py3-none-any.whl (632 kB)
Processing /Users/sagungargs/Library/Caches/pip/wheels/a9/b1/c7/cd2c3040de24952a0767ac58e59c06069cfe3b3c0e7f09ae42/HermesCache-0.7.2-py3-none-any.whl
Collecting python-magic<0.5,>=0.4
  Using cached python_magic-0.4.15-py2.py3-none-any.whl (5.5 kB)
Collecting ldap3<2.6,>=2.2.4
  Using cached ldap3-2.5.2-py2.py3-none-any.whl (393 kB)
Requirement already satisfied: pytz>=2015.4 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from superdesk-core->-r requirements.txt (line 5)) (2019.3)
Processing /Users/sagungargs/Library/Caches/pip/wheels/6a/76/b4/f97e26f8f60b5b2b1287415f1202e2b34a97775cead74072be/tzlocal-1.5.1-py3-none-any.whl
Collecting raven[flask]<7.0,>=5.10
  Using cached raven-6.10.0-py2.py3-none-any.whl (284 kB)
Requirement already satisfied: requests<3.0,>=2.7.0 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from superdesk-core->-r requirements.txt (line 5)) (2.23.0)
Collecting boto3<1.6,>=1.1.4
  Using cached boto3-1.5.36-py2.py3-none-any.whl (128 kB)
Collecting websockets<7.0,>=3.0
  Using cached websockets-6.0-cp37-cp37m-macosx_10_6_intel.whl (81 kB)
Processing /Users/sagungargs/Library/Caches/pip/wheels/09/65/b3/3773199f2de5f3371155c7caf2c0c1f4595d166d52c8f9cec6/mongolock-1.3.4-py3-none-any.whl
Processing /Users/sagungargs/Library/Caches/pip/wheels/06/a6/83/224e726cacb89d8d459811ac7c30825ef0afb75192fe934f22/PyYAML-4.2b4-cp37-cp37m-macosx_10_14_x86_64.whl
Processing /Users/sagungargs/Library/Caches/pip/wheels/ef/74/a1/fbc8be2438fe502684c7360b54264e38efc0e1190fc2603d8e/lxml-4.1.1-cp37-cp37m-macosx_10_14_x86_64.whl
Processing /Users/sagungargs/Library/Caches/pip/wheels/3b/af/89/2ead8345bfa6f4b95f3e2f836533fef2c5e764e9b4bf42d640/python_twitter-3.3-py3-none-any.whl
Requirement already satisfied: chardet<4.0 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from superdesk-core->-r requirements.txt (line 5)) (3.0.4)
Requirement already satisfied: pymongo<3.9,>=3.8 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from superdesk-core->-r requirements.txt (line 5)) (3.8.0)
Collecting croniter<0.4
  Using cached croniter-0.3.31-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: python-dateutil<2.8 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from superdesk-core->-r requirements.txt (line 5)) (2.7.5)
Collecting unidecode==0.04.21
  Using cached Unidecode-0.04.21-py2.py3-none-any.whl (228 kB)
Collecting authlib<0.13,>0.12
  Using cached Authlib-0.12.1-py2.py3-none-any.whl (181 kB)
Processing /Users/sagungargs/Library/Caches/pip/wheels/6d/6e/cd/4c2ed87d47697767da51e460eb5031c2e4e33e75037b90d736/draftjs_exporter-2.1.7-py3-none-any.whl
Requirement already satisfied: werkzeug<1.0 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from superdesk-core->-r requirements.txt (line 5)) (0.16.1)
Requirement already satisfied: cerberus<0.10,>=0.9.2 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from eve<=0.7.8,>=0.6->superdesk-core->-r requirements.txt (line 5)) (0.9.2)
Requirement already satisfied: events<0.3,>=0.2.1 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from eve<=0.7.8,>=0.6->superdesk-core->-r requirements.txt (line 5)) (0.2.2)
Requirement already satisfied: simplejson<4.0,>=3.3.0 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from eve<=0.7.8,>=0.6->superdesk-core->-r requirements.txt (line 5)) (3.17.0)
Requirement already satisfied: markupsafe<1.0,>=0.23 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from eve<=0.7.8,>=0.6->superdesk-core->-r requirements.txt (line 5)) (0.23)
Requirement already satisfied: jinja2<3.0,>=2.8 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from eve<=0.7.8,>=0.6->superdesk-core->-r requirements.txt (line 5)) (2.11.2)
Requirement already satisfied: itsdangerous<1.0,>=0.24 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from eve<=0.7.8,>=0.6->superdesk-core->-r requirements.txt (line 5)) (0.24)
Requirement already satisfied: ciso8601<2,>=1.0.2 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from eve-elastic==2.5.0->superdesk-core->-r requirements.txt (line 5)) (1.0.8)
Requirement already satisfied: elasticsearch<3.0.0,>=2.0.0 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from eve-elastic==2.5.0->superdesk-core->-r requirements.txt (line 5)) (2.4.1)
Requirement already satisfied: click>=2.0 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from flask<=0.12,>=0.10.1->superdesk-core->-r requirements.txt (line 5)) (7.1.1)
Requirement already satisfied: oauthlib!=2.0.3,!=2.0.4,!=2.0.5,<3.0.0,>=1.1.2 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from flask-oauthlib<0.10,>=0.9.3->superdesk-core->-r requirements.txt (line 5)) (2.1.0)
Requirement already satisfied: requests-oauthlib>=0.6.2 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from flask-oauthlib<0.10,>=0.9.3->superdesk-core->-r requirements.txt (line 5)) (1.3.0)
Requirement already satisfied: Babel>=2.3 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from flask-babel==0.12.2->superdesk-core->-r requirements.txt (line 5)) (2.8.0)
Requirement already satisfied: six>=1.4.1 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from bcrypt<3.2,>=3.1.1->superdesk-core->-r requirements.txt (line 5)) (1.14.0)
Collecting cffi>=1.1
  Using cached cffi-1.14.0-cp37-cp37m-macosx_10_9_x86_64.whl (174 kB)
Collecting vine>=1.3.0
  Using cached vine-1.3.0-py2.py3-none-any.whl (14 kB)
Collecting billiard<4.0,>=3.6.0
  Using cached billiard-3.6.3.0-py3-none-any.whl (89 kB)
Collecting amqp<3.0,>=2.4.0
  Using cached amqp-2.5.2-py2.py3-none-any.whl (49 kB)
Collecting pyasn1>=0.1.8
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Requirement already satisfied: idna<3,>=2.5 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from requests<3.0,>=2.7.0->superdesk-core->-r requirements.txt (line 5)) (2.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from requests<3.0,>=2.7.0->superdesk-core->-r requirements.txt (line 5)) (1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in /Users/sagungargs/pyvenv/lib/python3.7/site-packages (from requests<3.0,>=2.7.0->superdesk-core->-r requirements.txt (line 5)) (2020.4.5.1)
Collecting s3transfer<0.2.0,>=0.1.10
  Using cached s3transfer-0.1.13-py2.py3-none-any.whl (59 kB)
Collecting botocore<1.9.0,>=1.8.50
  Using cached botocore-1.8.50-py2.py3-none-any.whl (4.1 MB)
Collecting jmespath<1.0.0,>=0.7.1
  Using cached jmespath-0.9.5-py2.py3-none-any.whl (24 kB)
Processing /Users/sagungargs/Library/Caches/pip/wheels/56/b0/fe/4410d17b32f1f0c3cf54cdfb2bc04d7b4b8f4ae377e2229ba0/future-0.18.2-py3-none-any.whl
Collecting cryptography
  Using cached cryptography-2.9-cp35-abi3-macosx_10_9_intel.whl (1.7 MB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting docutils>=0.10
  Using cached docutils-0.16-py2.py3-none-any.whl (548 kB)
Installing collected packages: pillow, asyncio, pycparser, cffi, bcrypt, vine, amqp, kombu, billiard, redis, celery, feedparser, hachoir, HermesCache, python-magic, pyasn1, ldap3, tzlocal, raven, docutils, jmespath, botocore, s3transfer, boto3, websockets, mongolock, PyYAML, lxml, future, python-twitter, croniter, unidecode, cryptography, authlib, draftjs-exporter, superdesk-core, superdesk-analytics
  Attempting uninstall: pillow
    Found existing installation: Pillow 6.2.1
    Uninstalling Pillow-6.2.1:
      Successfully uninstalled Pillow-6.2.1
    Running setup.py install for pillow ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/sagungargs/pyvenv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/9n/c15s3xmd7w1bnhh9t0ksx4c80000gn/T/pip-install-fdte2gkq/pillow/setup.py'"'"'; __file__='"'"'/private/var/folders/9n/c15s3xmd7w1bnhh9t0ksx4c80000gn/T/pip-install-fdte2gkq/pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/9n/c15s3xmd7w1bnhh9t0ksx4c80000gn/T/pip-record-72_ub7an/install-record.txt --single-version-externally-managed --compile --install-headers /Users/sagungargs/pyvenv/include/site/python3.7/pillow
         cwd: /private/var/folders/9n/c15s3xmd7w1bnhh9t0ksx4c80000gn/T/pip-install-fdte2gkq/pillow/
    Complete output (174 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14-x86_64-3.7
    creating build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/MpoImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/ImageMode.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/PngImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/XbmImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/PcxImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/SunImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/ImageFile.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/SpiderImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/TarIO.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/FitsStubImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/MpegImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/BdfFontFile.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/GribStubImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/ImageStat.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/PixarImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/GimpPaletteFile.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/version.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/ImageColor.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/ContainerIO.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/MspImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/MicImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/ImtImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/GifImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/PalmImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/ImageQt.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/ImageMath.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/PaletteFile.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/FontFile.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/ExifTags.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/ImageCms.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/FpxImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/ImageChops.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/BufrStubImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/PSDraw.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/PcdImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/ImageFilter.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/ImageDraw2.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/ImagePath.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/DcxImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/JpegPresets.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/features.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/ImageDraw.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/GimpGradientFile.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/ImageWin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/IcoImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/_tkinter_finder.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/EpsImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/TgaImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/ImageMorph.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/WalImageFile.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/PcfFontFile.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/ImageTk.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/GbrImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/ImageOps.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/PdfImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/ImageShow.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/ImageEnhance.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/WmfImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/ImageGrab.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/WebPImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/FliImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/TiffTags.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/CurImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/_util.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/GdImageFile.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/TiffImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/IptcImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/ImagePalette.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/BmpImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/ImageTransform.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/IcnsImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/McIdasImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/XpmImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/OleFileIO.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/DdsImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/ImageSequence.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/PyAccess.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/_binary.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/Image.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/XVThumbImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/SgiImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/ImImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/PsdImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/JpegImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/ImageFont.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/PpmImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    copying src/PIL/FtexImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
    running egg_info
    writing src/Pillow.egg-info/PKG-INFO
    writing dependency_links to src/Pillow.egg-info/dependency_links.txt
    writing top-level names to src/Pillow.egg-info/top_level.txt
    reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching 'codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching '.travis'
    warning: no previously-included files found matching '.travis/*'
    warning: no previously-included files found matching 'appveyor.yml'
    warning: no previously-included files found matching 'build_children.sh'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
    running build_ext
    
    
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    Traceback (most recent call last):
      File "/private/var/folders/9n/c15s3xmd7w1bnhh9t0ksx4c80000gn/T/pip-install-fdte2gkq/pillow/setup.py", line 792, in <module>
        zip_safe=not (debug_build() or PLATFORM_MINGW), )
      File "/Users/sagungargs/pyvenv/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/sagungargs/pyvenv/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/private/var/folders/9n/c15s3xmd7w1bnhh9t0ksx4c80000gn/T/pip-install-fdte2gkq/pillow/setup.py", line 580, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: zlib
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/9n/c15s3xmd7w1bnhh9t0ksx4c80000gn/T/pip-install-fdte2gkq/pillow/setup.py", line 804, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    
    ----------------------------------------
  Rolling back uninstall of Pillow
  Moving to /Users/sagungargs/pyvenv/lib/python3.7/site-packages/PIL/
   from /Users/sagungargs/pyvenv/lib/python3.7/site-packages/~IL
  Moving to /Users/sagungargs/pyvenv/lib/python3.7/site-packages/Pillow-6.2.1.dist-info/
   from /Users/sagungargs/pyvenv/lib/python3.7/site-packages/~illow-6.2.1.dist-info
ERROR: Command errored out with exit status 1: /Users/sagungargs/pyvenv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/9n/c15s3xmd7w1bnhh9t0ksx4c80000gn/T/pip-install-fdte2gkq/pillow/setup.py'"'"'; __file__='"'"'/private/var/folders/9n/c15s3xmd7w1bnhh9t0ksx4c80000gn/T/pip-install-fdte2gkq/pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/9n/c15s3xmd7w1bnhh9t0ksx4c80000gn/T/pip-record-72_ub7an/install-record.txt --single-version-externally-managed --compile --install-headers /Users/sagungargs/pyvenv/include/site/python3.7/pillow Check the logs for full command output.
(pyvenv) Saguns-MacBook-Pro:server sagungargs$
