### ISSUE TITLE
superdesk/client/node_modules/superdesk-core/tasks/options/ngtemplates.js" not found

### ISSUE THREAD

**Issue by th3root** [superdesk/superdesk#3139]
i got problem when running command grunt server

WARNING: You are currently running a version of TypeScript which is not officially supported by typescript-eslint-parser.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: ~2.3.2

YOUR TYPESCRIPT VERSION: 3.7.2

Please only submit bug reports when using the officially supported version.

=============
Running "clean:dist" (clean) task
>> 1 path cleaned.

Running "clean:server" (clean) task
>> 0 paths cleaned.

Running "ngtemplates:index" (ngtemplates) task
>> Template "/home/rudi/superdesk/client/node_modules/superdesk-core//home/rudi/superdesk/client/node_modules/superdesk-core/tasks/options/ngtemplates.js" not found.
File ./index.html created.

Running "copy:index" (copy) task
Copied 1 file

Running "copy:config" (copy) task
Copied 1 file

Running "copy:locales" (copy) task
Copied 801 files

Running "nggettext_compile:all" (nggettext_compile) task

Running "ngtemplates:gen-apps" (ngtemplates) task
>> Template "/home/rudi/superdesk/client/node_modules/superdesk-core//home/rudi/superdesk/client/node_modules/superdesk-core/tasks/options/ngtemplates.js" not found.
File dist/app-importer.generated.js created.

Running "ngtemplates:dev" (ngtemplates) task
>> No templates found
File /home/rudi/superdesk/client/node_modules/superdesk-core/templates-cache.generated.js created.

Running "webpack-dev-server:start" (webpack-dev-server) task
 10% building modules 1/1 modules 0 activeFatal error: listen EADDRINUSE 0.0.0.0:9000

Please help

Thanks in advance

**Comment by petrjasek** [comment]
hi, seems like something is using port 9000

**Comment by th3root** [comment]
i've changed port 9000 so it's worked now. thanks

**Comment by petrjasek** [comment]
ok cool
