### ISSUE TITLE
How to upgrade Superdesk

### ISSUE THREAD

**Issue by trondhuso** [superdesk/superdesk#3162]
Hi

I am currently running an older version of superdesk. Believe it is 1.14 or something and the latest version is 1.33.
SO my question is: how to upgrade? Is it as simple as running the install script once more, or is it - as I am expecting - a bit more complicated?

The system is currently in production, so that is another challenge.

**Comment by trondhuso** [comment]
Someone told me the best option is to make a new folder and install the new version there. Then point ngnix or the web server you are using to the new directory.

**Comment by petrjasek** [comment]
hi, you can do that, anyhow you will have to run data migration via `manage.py data:upgrade` and also `manage.py app:initialize_data` after the update to fix/populate any missing data. it might also make sense to rebuild elastic index after that (`manage.py app:rebuild_elastic_index`), I suppose there were some mapping changes done meanwhile

**Comment by trondhuso** [comment]
I am closing this issue (since I started it) since it has an answer from SourceFabric.
