### ISSUE TITLE
How to resolve ImportError: No module named 'superdesk'

### ISSUE THREAD

**Issue by keshavadk** [superdesk/superdesk#3172]
I am trying to run the file email_formatter.py

and getting following error python email_formatter.py

```
Traceback (most recent call last):
  File "email_formatter.py", line 12, in <module>
    import superdesk
ImportError: No module named 'superdesk'
```

**Comment by petrjasek** [comment]
how do you run it?

**Comment by keshavadk** [comment]
I cloned the superdesk folder to my local machine and ran using VS code.

**Comment by petrjasek** [comment]
you have to setup python environment and install dependencies there

**Comment by keshavadk** [comment]
Yea Sir,i did set up Python environment, and installed superdesk by looking into superdesk webpage
i.e.      sudo apt-get install curl -y && curl -s https://raw.githubusercontent.com/takeit/superdesk-install/master/install | sudo bash

**Comment by petrjasek** [comment]
I mean in vscode if you run the script there

**Comment by keshavadk** [comment]
Yes.did that

**Comment by petrjasek** [comment]
can you paste here the full terminal output from the vscode?

**Comment by keshavadk** [comment]
Sure.
![VS_code](https://user-images.githubusercontent.com/16021947/83226175-fd03a280-a19e-11ea-8fe6-0a84a1a520dd.png)

**Comment by keshavadk** [comment]
Traceback (most recent call last):
  File "email_formatter.py", line 12, in <module>
    import superdesk
ModuleNotFoundError: No module named 'superdesk'

**Comment by petrjasek** [comment]
you have to activate the environment there first via `source <path-to-env>` but executing that file won't do much anyhow

**Comment by keshavadk** [comment]
Ok. Thank you. I will do that now.

**Comment by keshavadk** [comment]
The reason for me asking the query is , i wanted to understand the scripts from formatter folder and then 
have to convert NewsML to Article JSON and store that in Mongodb.
can i know where to start for understanding ?

**Comment by keshavadk** [comment]
Can i know at high level what :
1. email_formatter.py does ? and what
        email_article_subject.txt
        email subject
        email_article_body.txt
        email text content
        email_article_body.html
        email html content
2.  In the same way ,what newsml_1_2_formatter.py,newsml_g2_formatter.py,ninjs_formatter.py,ninjs_ftp_formatter.py,ninjs_newsroom_formatter.py,nitf_formatter.py   does?

Also in Transmitter folder:
email.py, file_output.py, ftp.py, http_push.py, odbc.py.

**Comment by petrjasek** [comment]
you can find some info [in the docs](https://superdesk.readthedocs.io/en/latest/)

> 1. email_formatter.py does ? and what
>    email_article_subject.txt
>    email subject
>    email_article_body.txt
>    email text content
>    email_article_body.html
>    email html content

email formatter creates an email from content item.
those html/txt files are jinja tempaltes which we use to do that. it makes it possible to customize
the output without touching the code.

> 2. In the same way,what  newsml_1_2_formatter.py,newsml_g2_formatter.py,ninjs_formatter.py,ninjs_ftp_formatter.py,ninjs_newsroom_formatter.py,nitf_formatter.py   does?

each does format the content in a different way eg [newsml](https://iptc.org/standards/newsml-g2/) or [ninjs](https://iptc.org/standards/ninjs/)

> Also in Transmitter folder:
> email.py, file_output.py, ftp.py, http_push.py, odbc.py.

these are the ways how clients can receive those formatted files.

**Comment by keshavadk** [comment]
Ok. Thank you very much for this information.

**Comment by keshavadk** [comment]
1. What exactly NewsML format? As i understood ,the NewsML format is XML format.
2.What is NITF and where it is used ?
3.NINJS ,is the JSON format used for sending and receiving .??
4. Can i also know what is metadata(Photo and video)?

I also need to convert  NewsML to **Article JSON** using python .   Can i use library available to convert XML to JSON or any other specific library i shall use?

**Comment by petrjasek** [comment]
you can check those formats on [iptc website](https://iptc.org/standards/)

**Comment by keshavadk** [comment]
Ok.Thank you.

**Comment by keshavadk** [comment]
Hi, 
     As a beginner for running the script ,what will be the starting point (starting script) to format an email or to create an email that is formatted. 

I have created 3 files (in same folder as email_formatter.py ) : 
- email_article_body.html 
- email_article_body.txt
- email_article_subject.txt
 
But not sure what file to execute to create an email from the content item. 

Thank you.

**Comment by keshavadk** [comment]
Hi Sir.

**Comment by keshavadk** [comment]
I wanted to execute the email_formatter.py in my local machine from visual studio code editor. 

Here i want to try without  **superdesk** module in my local machine. 

I mean to say ,the module dependencies for running particular file email_formatter.py.

**Comment by keshavadk** [comment]
Can i know what is the type of article(format type) to the fucntion **format()** in email_formatter.py?

**Comment by keshavadk** [comment]
Can you guide me ,from where i can start writing the formatter folder code from scratch using NewsML guidelines and python language?

**Comment by petrjasek** [comment]
not sure what is your usecase and how does it relate to superdesk..

**Comment by keshavadk** [comment]
Can i know the use of render_template ()  in email_formatter.py?

Thank you.

**Comment by keshavadk** [comment]
Hi,
       My use case is to create an email template and send .

Can i know the use of render_template () in email_formatter.py?

Thank you.
