### ISSUE TITLE
Docker installation not working

### ISSUE THREAD

**Issue by jl2035** [superdesk/superdesk#3212]
Hi, I'm getting the following error:

> superdesk@super:~/superdesk$ docker-compose up -d
> Removing elastic
> redis is up-to-date
> postfix is up-to-date
> mongodb is up-to-date
> Starting cf1549a4a5ce_elastic ... 
> Starting cf1549a4a5ce_elastic ... error
> 
> ERROR: for cf1549a4a5ce_elastic  Cannot start service elastic: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:378: setting rlimits for ready process caused \\\"error setting rlimit type 8: operation not permitted\\\"\"": unknown
> 
> ERROR: for elastic  Cannot start service elastic: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:378: setting rlimits for ready process caused \\\"error setting rlimit type 8: operation not permitted\\\"\"": unknown
> ERROR: Encountered errors while bringing up the project.

Am I doing something wrong?

**Comment by nickdbush** [comment]
Hi @jl2035, could you confirm your system specifications? How much memory does the host have? The compose file works on my 8GB machine.

**Comment by jl2035** [comment]
@nickdbush I added more RAM it's still not working.

> superdesk@super:~/superdesk$ free -h
>               total        used        free      shared  buff/cache   available
> Mem:           8.0G        206M        7.4G        112K        426M        7.8G
> Swap:          8.0G        1.0G        7.0G
> superdesk@super:~/superdesk$ docker-compose up -d
> redis is up-to-date
> postfix is up-to-date
> mongodb is up-to-date
> Starting cf1549a4a5ce_elastic ... 
> Starting cf1549a4a5ce_elastic ... error
> 
> ERROR: for cf1549a4a5ce_elastic  Cannot start service elastic: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:378: setting rlimits for ready process caused \\\"error setting rlimit type 8: operation not permitted\\\"\"": unknown
> 
> ERROR: for elastic  Cannot start service elastic: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:378: setting rlimits for ready process caused \\\"error setting rlimit type 8: operation not permitted\\\"\"": unknown
> ERROR: Encountered errors while bringing up the project.

**Comment by jl2035** [comment]
I've also tried manual installation on a separate clean and fresh lxc container (Ubuntu 18.04) behind nginx (on a different host) and was not successful. But I did get much further. Now I keep getting the "Invalid Host header" message on a blank page (no html).

@nickdbush Can you please describe the perfect environment where this would install automatically without issues?

**Comment by nickdbush** [comment]
@jl2035 could you try using these instructions? https://gist.github.com/nickdbush/95d8dfee0fa49d8b4635ceac2d264a9d

I've built some images for you:

1. https://hub.docker.com/repository/docker/nickdbush/superdesk-server
2. https://hub.docker.com/repository/docker/nickdbush/superdesk-client

There are still a few issues with these instructions but hopefully it will resolve the errors you currently have, and then we can move on to fixing the last few. Keep me updated with how it goes.

**Comment by jl2035** [comment]
@nickdbush on the server I run into the same problem:

ERROR: for superdesk_elastic_1  Cannot start service elastic: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:378: setting rlimits for ready process caused \\\"error setting rlimit type 8: operation not permitted\\\"\"": unknown

It did work locally on my laptop. There must be some difference between laptop and my server lxc infrastructure. Other docker applications work OK on lxc though.

**Comment by nickdbush** [comment]
This sounds like it could be an issue with elasticsearch: have you tried running an elastic container by itself following their instructions?

**Comment by jl2035** [comment]
Good point. But let me first try with a VM. Will report here.

**Comment by jl2035** [comment]
@nickdbush I think I got much further on a VM + docker. I think it's running and docker-compose file worked. Now I'm getting the blank home page.

See here: https://superdesk.dkk.ninja

There is nginx in front of it and can't find any good instructions on superdesk behind nginx.

**Comment by nickdbush** [comment]
What kind of information would you be looking for?

**Comment by jl2035** [comment]
Well, my nginx configuration looks like this:

```
server {
  listen    443;
  server_name superdesk.dkk.ninja;

  ssl on;
  ssl_certificate   /path/to/fullchain.pem;
  ssl_certificate_key /path/to/privkey.pem;
  keepalive_timeout   100;
  client_max_body_size 100M;

  location / {
    proxy_pass http://[SUPERDESK_BACKEND_SERVER_IP]:8080$request_uri;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}

server {
  listen    80;
  server_name superdesk.dkk.ninja;
  add_header Strict-Transport-Security max-age=2592000;
  rewrite ^/.*$ https://superdesk.dkk.ninja$request_uri? permanent;
}
```

If you visit the url you will see that javascript complains with the following error:

> Uncaught (in promise) DOMException: The operation is insecure. app.bundle.f7a596ce.js:170
>     f https://superdesk.dkk.ninja/app.bundle.f7a596ce.js:170
>     r https://superdesk.dkk.ninja/app.bundle.f7a596ce.js:170
>     o https://superdesk.dkk.ninja/app.bundle.f7a596ce.js:289
>     ct https://superdesk.dkk.ninja/app.bundle.f7a596ce.js:289
>     o https://superdesk.dkk.ninja/app.bundle.f7a596ce.js:289
>     ct https://superdesk.dkk.ninja/app.bundle.f7a596ce.js:289
>     r https://superdesk.dkk.ninja/app.bundle.f7a596ce.js:289
>     ce https://superdesk.dkk.ninja/app.bundle.f7a596ce.js:289
>     o https://superdesk.dkk.ninja/app.bundle.f7a596ce.js:160
>     (Async: promise callback)
>     o https://superdesk.dkk.ninja/app.bundle.f7a596ce.js:160
>     <anonymous> https://superdesk.dkk.ninja/app.bundle.f7a596ce.js:779
>     (Async: setTimeout handler)
>     <anonymous> https://superdesk.dkk.ninja/app.bundle.f7a596ce.js:779
>     t https://superdesk.dkk.ninja/app.bundle.f7a596ce.js:1
>     <anonymous> https://superdesk.dkk.ninja/app.bundle.f7a596ce.js:779
>     t https://superdesk.dkk.ninja/app.bundle.f7a596ce.js:1
>     <anonymous> https://superdesk.dkk.ninja/app.bundle.f7a596ce.js:160
>     t https://superdesk.dkk.ninja/app.bundle.f7a596ce.js:1
>     <anonymous> https://superdesk.dkk.ninja/app.bundle.f7a596ce.js:170
>     t https://superdesk.dkk.ninja/app.bundle.f7a596ce.js:1
>     <anonymous> https://superdesk.dkk.ninja/app.bundle.f7a596ce.js:1
>     <anonymous> https://superdesk.dkk.ninja/app.bundle.f7a596ce.js:1

So is my nginx configuration missing something or is there something else wrong with my setup?

**Comment by nickdbush** [comment]
From a secure HTTPS context, you can't communicate to websocket over an insecure ```ws://``` connection. You must use ```wss://```. You'll need to update the `SUPERDESK_WS_URL` parameter in the `docker-compose.yml` file.

**Comment by jl2035** [comment]
@nickdbush YES, that was it. It's working now. Thanks!
