### ISSUE TITLE
Unable to install Superdesk

### ISSUE THREAD

**Issue by mairajha** [superdesk/superdesk#3219]
I am unable to install superdesk via given command - any help will be appreciated

sudo apt-get install curl -y && curl -s https://raw.githubusercontent.com/takeit/superdesk-install/master/install | sudo bash

**Comment by nickdbush** [comment]
Hi @mairajha, what exactly went wrong? It's also difficult for us to give advice on external install scripts (as we don't maintain them). We have some new Docker containers coming out very shortly which should help with most installation purposes though.

**Comment by mairajha** [comment]
![image](https://user-images.githubusercontent.com/52917522/106467109-07a8d100-64be-11eb-86b3-47ea63ad8e6e.png) thanks for reply, this is the error I am facing right now

**Comment by mairajha** [comment]
> Hi @mairajha, what exactly went wrong? It's also difficult for us to give advice on external install scripts (as we don't maintain them). We have some new Docker containers coming out very shortly which should help with most installation purposes though.

That's great! When the new @Docker Containers will be out? Any specific date pls?

**Comment by nickdbush** [comment]
Hopefully by the end of the week, with a new set of documentation following shortly after

**Comment by mairajha** [comment]
> Hopefully by the end of the week, with a new set of documentation following shortly after

Thats a good news, then I should wait for a week then - will give it a try & hopefully the new docker is same like the previous one with simple installation with single command on CLI - thanks a lot. . .

**Comment by mairajha** [comment]
Is this out? Or any specific date for release?

**Comment by nickdbush** [comment]
Hi @mairajha, I'm pleased to announce that our containers have officially been released at https://hub.docker.com/u/sourcefabricoss!

**Comment by mairajha** [comment]
That's a great news. . .

**Comment by nickdbush** [comment]
As the original issue is now fixed, would you be able to close this @mairajha? Thanks!

**Comment by mairajha** [comment]
Sure
