### ISSUE TITLE
Docker - ERROR:superdesk:localhost:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description

### ISSUE THREAD

**Issue by arniesaha** [superdesk/superdesk#3230]
Hey Folks,

Looks like an interesting project. Was keen on setting it up to validate on a project requirement. 

Although, `docker-compose up -d ` brings up the containers. 

The init data:
`docker-compose run superdesk-server run python manage.py app:initialize_data`

Has an issue: 
`ERROR:superdesk:localhost:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 606bf70ff59b6bb720dc45fc, topology_type: Single, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused',)>]>
`
![superdesk-docker-init-error](https://user-images.githubusercontent.com/3646287/113665527-3d8b5100-96cb-11eb-8c20-e201f91d8f7f.png)

Although I'm able to ssh into the mongo container. 

And, this one does create a user:
`docker-compose run superdesk-server run python manage.py users:create -u admin -p admin -e admin@localhost --admin`

I can also see a git action for the server failed on the last commit:
https://github.com/superdesk/superdesk/actions/runs/715608744

Could this be related?

Will try setting up natively, although if docker works that would be great. 

Also, without initializing also not able to create a desk within the client dashboard (as the Desk Type dropdown is empty and is a required field)

![dashboard-desk-type-empty](https://user-images.githubusercontent.com/3646287/113665993-1b460300-96cc-11eb-8db0-be79b46ae1d9.png)

Thanks for any assistance!

**Comment by nickdbush** [comment]
Hi @arniesaha -- this is an issue that I am actively tracking; thanks for your detailed report! Can you give the containers from https://hub.docker.com/u/nickdbush a whirl and see if you have any luck with them?

**Comment by nickdbush** [comment]
The containers under /u/sourcefabricoss are built from the demo branch, whereas the containers under /u/nickdbush were built from the main branch (5 months ago). I'll raise an issue with our dev team.

**Comment by arniesaha** [comment]
Hi @nickdbush thanks for the revert. Tried changing the containers to 

`  superdesk-server:
    image: nickdbush/superdesk-server:latest`
`  superdesk-client:
    image: nickdbush/superdesk-client:latest`
    
    in docker-compose.yml -> removed the old containers & images -> `docker-compose up -d `

But, the init error mentioned in the main post is still the same. 

Is there a db dump perhaps of mongo? That could be used to import/seed the mongo container?

**Comment by nickdbush** [comment]
@arniesaha the images on Docker Hub have been rebuilt to include #3231, let us now how that goes

**Comment by arniesaha** [comment]
The last changes fixed the issue +1
