### ISSUE TITLE
Initial Setup: Page Not Loading

### ISSUE THREAD

**Issue by Aaronjacobs678** [superdesk/superdesk#3245]
Good Evening! 

Please exscuse me, I am very new to linux server distributions. I have followed the setup instructions on the ReadMe, and on first loading the page after running up the server and client on Linux, I am just being presenter with a Fav Icon, Site title and blank page (http://151.236.61.57:9000/). 

All I can see is a blocked connection (?CORS?) on the client_config. Could this be causing it?

![image](https://user-images.githubusercontent.com/61187426/121107019-10f4d200-c7ff-11eb-9d78-4820fdefac8a.png)

Sorry about the little information to go on, I just really don't know what to think! The website will be kept live if you may have any thoughts on the issue? 

Thanks for your help in advance!

Aaron

**Comment by nickdbush** [comment]
Hi Aaron, I can't seem to connect to http://151.236.61.57:9000/ (connection refused). Can you confirm for me the value of the `SUPERDESK_CLIENT_URL` environment variable?

**Comment by Aaronjacobs678** [comment]
Hello! Back up now, there was errors with the webhost throughout the day. I am sorry - how am I locating that environment variable?
Thanks :-)
