### ISSUE TITLE
Desk Management - Add Desk Issue

### ISSUE THREAD

**Issue by Aaronjacobs678** [superdesk/superdesk#3247]
Good Morning -

After trying multiple installation methods on different OS, Mongo & Elastic versions I am unable to correct the following error (tried in different browsers, this is taken from Firefox). A few fields (such as DESK TYPE) has no options to select from. It's just blank. Potential errors below?

![err1](https://user-images.githubusercontent.com/61187426/122191983-25823b80-ce8b-11eb-9103-1bd09c5477dc.JPG)
![err2](https://user-images.githubusercontent.com/61187426/122191992-261ad200-ce8b-11eb-8782-f153e81b89a0.png)

**Comment by Aaronjacobs678** [comment]
Added Photo from Terminal on Install - 
![err3](https://user-images.githubusercontent.com/61187426/122384845-fee40380-cf63-11eb-9fba-1c21418b9508.JPG)

**Comment by nickdbush** [comment]
Hi Aaron, did you run the initialize data command?

**Comment by Aaronjacobs678** [comment]
Hi Nick! I believe so... I am just doing a fresh install on Ubuntu 18 now, and will let you know...

**Comment by Aaronjacobs678** [comment]
A potentially unrelated error, however we appear to be stuck here on the installation - could this be because we are attempting to install from a root user?

![err4](https://user-images.githubusercontent.com/61187426/122390640-22aa4800-cf6a-11eb-9dc5-a4fc4206c395.JPG)

**Comment by Aaronjacobs678** [comment]
I have done three more installs on varying OS and all have surcombe to the error above.

**Comment by nickdbush** [comment]
Thanks for that information! Setting the desk types sounds like something that needs to be modified in the controlled vocabulary.

**Comment by Aaronjacobs678** [comment]
Okay, thanks Nick! Any thoughts on the install fork error, shown above? Really cannot get my head around it! :-)

**Comment by Aaronjacobs678** [comment]
> 
> 
> Hi Nick -
> 
> I am unable to recall how I got past this last time. A potentially unrelated error, however we appear to be stuck here on the installation. Any thoughts?
> 
> ![err4](https://user-images.githubusercontent.com/61187426/122390640-22aa4800-cf6a-11eb-9dc5-a4fc4206c395.JPG)

Any news in this error? :-)

**Comment by petrjasek** [comment]
hi, there is no error really on that screenshot.

if you go to settings > metadata do you see any vocabularies?

**Comment by Aaronjacobs678** [comment]
Good Morning Petr! I hope you are well. The install at this point appears to just slow right down and never appears to finish? Just seems to repeat the forking error?

I am in the middle of a re-install so will get back to you about the above point!  :-)

**Comment by Aaronjacobs678** [comment]
> 
> 
> hi, there is no error really on that screenshot.
> 
> if you go to settings > metadata do you see any vocabularies?

@petrjasek 
Yes - Vocabularies: 
![err6](https://user-images.githubusercontent.com/61187426/122760060-957d3100-d292-11eb-842a-63c31adaedfa.JPG)

**Comment by petrjasek** [comment]
can you pull from github and try again?

**Comment by petrjasek** [comment]
l mean pull and reinstall

**Comment by Aaronjacobs678** [comment]
Doing Now! :-)

**Comment by Aaronjacobs678** [comment]
@petrjasek - The Desk issue appears to be resolved! Was there much that needed ammending? :-)

**Comment by Aaronjacobs678** [comment]
Thanks for all your help!
