### ISSUE TITLE
Users Dissapeared

### ISSUE THREAD

**Issue by Aaronjacobs678** [superdesk/superdesk#3249]
Hi All -

My users seemed to have all vanished. I cannot login, even with 'admin' which was never changed. I added some other users accounts that I am not able to login as, and when using 'forgot password' states the email does not exist. Where can I check for the users? The only thing I have changed is the default app name and email settings in the settings.py

Many thanks!

**Comment by petrjasek** [comment]
hi, check in mongodb, superdesk database. if you have changed `MONGO_DBNAME` config as well that could be the issue

**Comment by Aaronjacobs678** [comment]
I could not find a .users table within the MongoDB. I assume this is what I am looking for?

**Comment by Aaronjacobs678** [comment]
Is this build in mongo correct?
![err10](https://user-images.githubusercontent.com/61187426/124265062-2672c880-db2d-11eb-863f-f3abbfbb3718.JPG)

**Comment by Aaronjacobs678** [comment]
****UPDATE****
Researching this issue has shown me that for a while an online malicious code has been targeting websites and dropping all of the databases off MongoDB - any database that has not been secured (which we havent due to testing). This is what has been dropping the ability to login!
