### ISSUE TITLE
Images & Other Content Query

### ISSUE THREAD

**Issue by Aaronjacobs678** [superdesk/superdesk#3251]
Good Evening!

When I upload a  Featured Image to an article and Publish to website - why is the image created into its own element in the working stage? It then remains there in the Working Stage after I have published the article to the Output stage.

Otherwise I am just collating images! Can these be stored anywhere for future use?

Is this an issue?

![err13](https://user-images.githubusercontent.com/61187426/124642538-dd51aa00-de87-11eb-8b9a-810b9400f548.JPG)

**Comment by petrjasek** [comment]
you can set in `server/settings.py`
```py
PUBLISH_ASSOCIATED_ITEMS = True
```
and it will autopublish associated images so those will become part of the output and not stay in progress

**Comment by Aaronjacobs678** [comment]
Thanks @petrjasek ! Maybe this could be added to the ReadTheDocs documentation?
