### ISSUE TITLE
Install Issue <36hours

### ISSUE THREAD

**Issue by Aaronjacobs678** [superdesk/superdesk#3253]
Good Afternoon Team - 

Since the last 36 hours, an installation issue has cropped up. Installing onto Ubuntu 20.04, I am getting the following error with the Grunt Build. I have performed multiple installs over the last few weeks, with the most recent being two days ago - and all these performed as expected. 

ERROR in ./index.js
Module not found: Error: Can't resolve 'superdesk-core/scripts/extensions/annota                                                        tionsLibrary' in '/opt/superdesk/client'
 @ ./index.js 27:96-159
 @ ./dist/app-importer.generated.js
 @ ./node_modules/superdesk-core/scripts/index.ts
 @ multi ./node_modules/superdesk-core/scripts/index

ERROR in ./index.js
Module not found: Error: Can't resolve 'superdesk-core/scripts/extensions/dateti                                                        meField' in '/opt/superdesk/client'
 @ ./index.js 35:96-154
 @ ./dist/app-importer.generated.js
 @ ./node_modules/superdesk-core/scripts/index.ts
 @ multi ./node_modules/superdesk-core/scripts/index

ERROR in ./index.js
Module not found: Error: Can't resolve 'superdesk-core/scripts/extensions/markFo                                                        rUser' in '/opt/superdesk/client'
 @ ./index.js 31:96-152
 @ ./dist/app-importer.generated.js
 @ ./node_modules/superdesk-core/scripts/index.ts
 @ multi ./node_modules/superdesk-core/scripts/index

ERROR in ./index.js
Module not found: Error: Can't resolve 'superdesk-planning/client/planning-exten                                                        sion' in '/opt/superdesk/client'
 @ ./index.js 39:96-151
 @ ./dist/app-importer.generated.js
 @ ./node_modules/superdesk-core/scripts/index.ts
 @ multi ./node_modules/superdesk-core/scripts/index

**Comment by Aaronjacobs678** [comment]
I have been able to resolve this issue by adding the full path to the files within the /client/index.js file (as below). Although I am assuming I should not have to be doing that...

`import {startApp} from 'superdesk-core/scripts/index';

setTimeout(() => {
    startApp(
        [
            {
                id: 'annotationsLibrary',
                load: () => import('/opt/superdesk/client/node_modules/superdesk-core/scripts/extensions/annotationsLibrary/src/extension'),
            },
            {
                id: 'markForUserExtension',
                load: () => import('/opt/superdesk/client/node_modules/superdesk-core/scripts/extensions/markForUser/src/extension'),
            },
            {
                id: 'datetimeFieldExtension',
                load: () => import('/opt/superdesk/client/node_modules/superdesk-core/scripts/extensions/datetimeField/src/extension'),
            },
            {
                id: 'planning-extension',
                load: () => import('/opt/superdesk/client/node_modules/superdesk-planning/client/planning-extension/src/extension'),
            },
        ],
        {},
    );
});

export default angular.module('main.superdesk', []);

`

**Comment by petrjasek** [comment]
try to run `npm run build` instead of `grunt build`

**Comment by Aaronjacobs678** [comment]
Will give it a go!

**Comment by Aaronjacobs678** [comment]
Now getting this -

```
Running "webpack:build" (webpack) task
 95% emittingCommand failed: cd /opt/superdesk/client/ && node --max-old-space-s                                                                                                                                                             ize=8192 ./node_modules/.bin/grunt build
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! superdesk@ build: `npx @superdesk/build-tools build-root-repo ./`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the superdesk@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                                                                                             ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-21T12_38_29_770Z-debug.log
root@id15904:~# ^C
root@id15904:~# nano /root/.npm/_logs/2021-07-21T12_38_29_770Z-debug.log
root@id15904:~# npm cache clean –force
npm ERR! npm cache clear does not accept arguments

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-21T12_47_42_966Z-debug.log
```

**Comment by Aaronjacobs678** [comment]
@petrjasek - Could not get NPM Build to work (as above). However I returned to using 'grunt build' and it appeared to have run fine. Must have been something my end. So will close this issue. Thanks for advice!
