### ISSUE TITLE
Superdesk: can no longer choose category

### ISSUE THREAD

**Issue by mathiasp** [superdesk/superdesk#3275]
I'm evaluating Superdesk for a literature review site for a friend. I created a few categories, all worked well the last few days.

Today  the following happened:

- I added a category
   - categories were no longer shown when editing an item and clicking on the  catgegory '+'-Icon. Typing in the search box gave no results.
- I edited categories again, adding translations (just to   change something)
   - now 3 out of 10 categories are shown
- I changed some category names (removed colons) 
   - now only 2 out of 10 categories are shown

Is there any kind of authorisation and/or configuration somewhere that controls which categories are shown?

Old items show all the categories that can no longer be choosen. If I delete them, I can no longer add them.

Any idea would be gladly accepted.

I checked in the firefox network tab: the vocabulariy query superdesk sends returns all categories, and the only error in the console are a few "duplicate reqest send".

Superdesk identifies as:

Superdesk eb4a4fc
superdesk: eb4a4fcdce0099eaeb2bd4ee8529859c48c4843e
superdesk-core: 2.3.0
superdesk-client-core: 5033a996f98ff2a4d07c98f495ff7eb7d85faed9
superdesk-planning: 2.3.0
superdesk-publisher: 4e20ba7431534dd00d992407e2b2f703e108f768

Thanks for any help,

Mathias

**Comment by petrjasek** [comment]
Hello, you can set user preferred categories in the user profile preferences, that might be doing the filtering
